CREATE TABLE ACCOUNT (
  id RAW(16) PRIMARY KEY,
  account_id VARCHAR2(50) NOT NULL,
  password VARCHAR2(8) NOT NULL
);

CREATE TABLE URL (
  id RAW(16) PRIMARY KEY,
  account RAW(16) ,
  name VARCHAR2(250) NOT NULL,
  redirect_type number(3,0) NOT NULL,
  call_number number(5) NOT NULL

  CONSTRAINT FK_ACCOUNT FOREIGN KEY (ACCOUNT) REFERENCES ACCOUNT(ID),
);

--CREATE TABLE ACCOUNT_URL (
--  account RAW(16) DEFAULT NULL,
--  url RAW(16) DEFAULT NULL
--
--  CONSTRAINT FK_ACCOUNT FOREIGN KEY (ACCOUNT) REFERENCES ACCOUNT(ID),
--  CONSTRAINT FK_URL FOREIGN KEY (URL) REFERENCES URL(ID)
--);